-   id: clang-format-docs
    name: clang-format-docs
    description: Run `clang-format` on C++ code blocks in documentation files.
    entry: clang-format-docs
    language: python
    language_version: python3
    types: [markdown]
